//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practos_6.youyou
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plays
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plays()
        {
            this.SostavArtists = new HashSet<SostavArtists>();
            this.ShowSchedule = new HashSet<ShowSchedule>();
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int PlayID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Director { get; set; }
        public Nullable<int> GenreID { get; set; }
        public Nullable<int> KolichMest { get; set; }
    
        public virtual Genres Genres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SostavArtists> SostavArtists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShowSchedule> ShowSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
