//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practos_6.youyou
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseHistory
    {
        public int PurchaseID { get; set; }
        public Nullable<int> AudienceID { get; set; }
        public Nullable<int> TicketID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
    
        public virtual Audience Audience { get; set; }
        public virtual Tickets Tickets { get; set; }
    }
}
