//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practos_6.youyou
{
    using System;
    using System.Collections.Generic;
    
    public partial class SostavArtists
    {
        public int Id_sostava { get; set; }
        public Nullable<int> PlayID { get; set; }
        public Nullable<int> ArtistID { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Artists Artists { get; set; }
        public virtual Plays Plays { get; set; }
    }
}
