//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practos_6.youyou
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tickets()
        {
            this.PurchaseHistory = new HashSet<PurchaseHistory>();
        }
    
        public int TicketID { get; set; }
        public Nullable<int> PlayID { get; set; }
        public Nullable<int> AudienceID { get; set; }
        public string SeatNumber { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> TicketTypeID { get; set; }
    
        public virtual Audience Audience { get; set; }
        public virtual Plays Plays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseHistory> PurchaseHistory { get; set; }
        public virtual TicketTypes TicketTypes { get; set; }
    }
}
